// Mocks generated by Mockito 5.3.2 from annotations
// in submission_final/test/ui/home/restaurant_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:submission_final/core/error/failure.dart' as _i6;
import 'package:submission_final/domain/entities/restaurant.dart' as _i7;
import 'package:submission_final/domain/repositories/restaurant_repository.dart'
    as _i2;
import 'package:submission_final/domain/usecases/get_list_restaurant.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRestaurantRepository_0 extends _i1.SmartFake
    implements _i2.RestaurantRepository {
  _FakeRestaurantRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetListRestaurant].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetListRestaurant extends _i1.Mock implements _i4.GetListRestaurant {
  MockGetListRestaurant() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RestaurantRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeRestaurantRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.RestaurantRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Restaurant>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Restaurant>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Restaurant>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Restaurant>>>);
}
